# Generated by Django 5.1.5 on 2025-02-02 12:47

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(default=datetime.datetime(2025, 2, 2, 12, 47, 48, 407162, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='student',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='students.student'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user_signature',
            field=models.CharField(blank=True, default='No user signature', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='paymentpackage',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
