# Generated by Django 5.1.5 on 2025-02-02 13:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_remove_paymentpackage_value_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='next_paymentdate',
            new_name='next_payment_date',
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(default=datetime.datetime(2025, 2, 2, 13, 17, 42, 54593, tzinfo=datetime.timezone.utc)),
        ),
    ]
