# Generated by Django 5.1.5 on 2025-02-03 17:25

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_rename_next_paymentdate_payment_next_payment_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='value',
        ),
        migrations.AddField(
            model_name='paymentvalue',
            name='method',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='methods', to='payments.paymentmethod'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(default=datetime.datetime(2025, 2, 3, 17, 25, 19, 625583, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='paymentvalue',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.payment'),
        ),
    ]
