# Generated by Django 5.1.5 on 2025-02-03 17:29

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_remove_payment_payment_method_remove_payment_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(default=datetime.datetime(2025, 2, 3, 17, 29, 18, 491218, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='paymentvalue',
            name='method',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='payment_methods', to='payments.paymentmethod'),
        ),
        migrations.AlterField(
            model_name='paymentvalue',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='values', to='payments.payment'),
        ),
    ]
