# Generated by Django 5.1.5 on 2025-02-06 00:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_alter_payment_payment_date_alter_paymentvalue_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(default=datetime.datetime(2025, 2, 6, 0, 53, 34, 545345, tzinfo=datetime.timezone.utc)),
        ),
    ]
