# Generated by Django 5.1.5 on 2025-02-06 19:31

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_alter_payment_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(default=datetime.date(2025, 2, 6)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_package',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='payments.paymentpackage'),
        ),
    ]
