# Generated by Django 5.1.5 on 2025-02-06 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_alter_payment_payment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_package',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='payments.paymentpackage'),
        ),
        migrations.AlterField(
            model_name='paymentvalue',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='payments.payment'),
        ),
    ]
