# Generated by Django 5.1.5 on 2025-02-11 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0002_student_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutExercice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trainings', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_day', models.CharField(choices=[('SUNDAY', 'DOMINGO'), ('MONDAY', 'SEGUNDA'), ('TUESDAY', 'TERÇA'), ('WEDNESDAY', 'QUARTA'), ('THURSDAY', 'QUINTA'), ('FRIDAY', 'SEXTA'), ('SATURDAY', 'SÁBADO')], max_length=20)),
                ('workout_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='trainings.workoutsheet')),
            ],
        ),
    ]
