# Generated by Django 5.1.5 on 2025-02-11 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutsheet',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='workoutsheet',
            name='user_signature',
            field=models.CharField(blank=True, default='No user signature', max_length=100, null=True),
        ),
    ]
