# Generated by Django 5.1.5 on 2025-02-12 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0003_workoutdayexercise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutday',
            name='week_day',
            field=models.CharField(choices=[('SUNDAY', 'DOMINGO'), ('MONDAY', 'SEGUNDA'), ('TUESDAY', 'TERÇA'), ('WEDNESDAY', 'QUARTA'), ('THURSDAY', 'QUINTA'), ('FRIDAY', 'SEXTA'), ('SATURDAY', 'SÁBADO')], max_length=10),
        ),
    ]
