# Generated by Django 5.1.5 on 2025-02-15 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0004_alter_workoutday_week_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutdayexercise',
            name='observations',
            field=models.TextField(default='', max_length=200),
        ),
    ]
