# Generated by Django 5.1.5 on 2025-02-16 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0005_workoutdayexercise_observations'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutsheet',
            name='observations',
            field=models.TextField(default='', max_length=200),
        ),
    ]
