# Generated by Django 5.1.5 on 2025-02-16 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0006_workoutsheet_observations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutdayexercise',
            name='workout_day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='trainings.workoutday'),
        ),
    ]
